@SecureOps.Api_HostAddress = https://localhost:7030

GET {{SecureOps.Api_HostAddress}}/weatherforecast/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoia2hhbGlkLm1hbGF0ZUBnb29nbGUuY29tIiwianRpIjoiOTFkZGVlNTQtMTk0Zi00NzNkLWIyNTgtMWE5MTVlMjAxMWExIiwiZXhwIjoxNzc1OTYxNDA5LCJpc3MiOiJTZWN1cmVPcHMuQXBpIiwiYXVkIjoiU2VjdXJlT3BzLkNsaWVudCJ9.dYAdCDRw8lmwzTiPoWi25BvmayQuki_CuK4lCUzdOyE

###

POST {{SecureOps.Api_HostAddress}}/authentication/register
Content-Type: application/json

{
  "Email" : "khalid.malate@google.com",
  "Password": "#e4u8IQEtroh",
  "FirstName": "Khalid",
  "LastName": "Malate",
  "SSNLastFour": "1234"
}

### Login (This will give you a Cookie or Token)
# If using Identity API Endpoints, this returns a Cookie by default
# or a Bearer token if you ask for it.

POST {{SecureOps.Api_HostAddress}}/login
Content-Type: application/json

{
  "email": "khalid.malate@google.com",
  "password": "#e4u8IQEtroh"
}

###


GET {{SecureOps.Api_HostAddress}}/fielddefinition

###

POST {{SecureOps.Api_HostAddress}}/fielddefinition
Content-Type: application/json

{
  "label" : "test",
  "FieldTypeId": 1
}

###

POST {{SecureOps.Api_HostAddress}}/authentication/login
Content-Type: application/json

{
  "email": "khalid.malate@google.com",
  "password": "#e4u8IQEtroh"
}

###
